project_id = "drpdlvpfzetsxgbbkcej"

[functions.generate-tasks]
verify_jwt = true

[functions.task-assistant]
verify_jwt = true

[functions.project-assistant]
verify_jwt = true

[functions.build-and-deploy]
verify_jwt = true